### ISSUE TITLE
RACFADM Install Question

### ISSUE THREAD

**Issue by hickorystix** [lbdyck/racfadm#1]
I cannot find any reference to the "RACF  SITE" program.  Where is it, and how do I update it per the instructions in the README file. I am using the latest CBT508 version, and running on several
instances of z/OS from 1.13S to 3.1.

Thanks,
Frank

**Comment by Janko-RACFADM** [comment]
The RACFSITE Rexx program is no longer used.  Option 0, Settings, has options for setting site specific information.

**Comment by hickorystix** [comment]
Thank you. I will investigate that. I appreciate the quick response.
Frank

**Comment by hickorystix** [comment]
Working Fine! Nice application. Closing.
